myapp/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import RegisterView, LoginView, MainpageView, HomeView, postrateView
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', MainpageView, name='main'),
    path('home/', login_required(HomeView)),
    path('register/', RegisterView, name='register'),
    path('login/', LoginView, name='login'),

    path('post/', views.PostList.as_view(), name='post_list'),
    path('post/<int:pk>', views.PostDetail.as_view(), name='post-detail'),
    path('post-new/', views.PostCreate.as_view(), name='post_new'),
    path('post-edit/<int:pk>', views.PostUpdate.as_view(), name='post-edit'),
    path('post-delete/<int:pk>', views.PostDelete.as_view(), name='post-delete'),
    path('post-rate/<int:pk>', views.postrateView, name='post-rate'),

    path('reply/<int:pk>', views.ReplyList.as_view(), name='reply_list'),
    path('reply-view/<int:pk>', views.ReplyDetail.as_view(), name='reply_detail'),
    path('reply-new/<int:pk>', views.ReplyCreate.as_view(), name='reply_new'),
    path('reply-edit/<int:pk>', views.ReplyUpdate.as_view(), name='reply_edit'),
    path('reply-delete/<int:pk>', views.ReplyDelete.as_view(), name='reply_delete'),

    path('question/', views.QuestionListView.as_view(), name='question-list'),
    path('question/<int:pk>', views.QuestionDetailView.as_view(), name='question-detail'),
    path('question-new/', views.QuestionCreate.as_view(), name='question-new'),

]

myproject/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from rest_framework import routers
from django.conf import settings
from django.conf.urls.static import static


from myapp import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'posts', views.PostViewSet)
router.register(r'replies', views.RepliesViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('serializer/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # path('ratings/', include('star_ratings.urls', namespace='ratings')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from _decimal import Decimal
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from django.db import models
from django.core.validators import FileExtensionValidator


# Create your models here.


class User(AbstractUser):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    username = models.CharField(max_length=50)
    email = models.EmailField(max_length=100, null=False, unique=True)
    password = models.CharField(max_length=255)
    address = models.CharField(max_length=20)
    birth_date = models.DateField(null=True, blank=True)
    photo = models.ImageField(upload_to='images/', max_length=100, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.first_name


class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    photo = models.ImageField(verbose_name='Imagen', upload_to='images/', blank=True, null=True, validators=[FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])
    created_date = models.DateTimeField(default=timezone.now)
    publish_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title


class Postratings(models.Model):
    # rater_count = models.PositiveIntegerField(default=0, null=True)
    rate = models.PositiveIntegerField(default=0, validators=[MinValueValidator(1), MaxValueValidator(5)], null=True)
    # count = models.PositiveIntegerField(default=0, null=True)
    average = models.DecimalField(max_digits=5, decimal_places=1, default=Decimal(0.0))
    post = models.ForeignKey('Post', null=True,  on_delete=models.CASCADE)
    user = models.ForeignKey('User', null=True, on_delete=models.CASCADE)

    # def __str__(self):
    #     return self.post


class Questions(models.Model):
    question = models.TextField()
    publish_date = models.DateTimeField(default=timezone.now)


class Questionratings(models.Model):
    rate = models.PositiveIntegerField(default=0, validators=[MinValueValidator(1), MaxValueValidator(5)], null=True)
    average = models.DecimalField(max_digits=5, decimal_places=2, default=Decimal(0.0))
    question = models.ForeignKey('Questions', null=True, on_delete=models.CASCADE)
    user = models.ForeignKey('User', null=True, on_delete=models.CASCADE)


class Replies(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

myapp/forms.py
from django import forms

from myapp.models import Postratings, Replies, Questionratings, Post


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'form-control form-control-md'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control form-control-md'}))
# class SignupForm(forms.Form):
#     name = forms.CharField(label='Your Name', max_length=100)


class RegisterForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First Name', 'class': 'form-control form-control-md'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Last Name', 'class': 'form-control form-control-md'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username', 'class':'form-control form-control-md'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Address', 'class': 'form-control form-control-md'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'form-control form-control-md'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control form-control-md'}))
    # birth_date = forms.DateField(null=True, blank=True)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'photo', 'created_date', 'publish_date']

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['photo'].required = False

class PostRateForm(forms.ModelForm):
    class Meta:
        model = Postratings
        fields = ['rate']


class QuestionRateForm(forms.ModelForm):
    class Meta:
        model = Questionratings
        fields = ['rate']

class ReplyPostForm(forms.ModelForm):
    class Meta:
        model = Replies
        fields = ['text', 'created_date']

myapp/views.py
from itertools import count

from django.contrib.auth import authenticate, login
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import request, HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.views.generic.base import View
from django.shortcuts import render
from .forms import LoginForm, RegisterForm, PostRateForm, ReplyPostForm, QuestionRateForm, PostForm
from .models import User, Post, Replies, Postratings, Questions, Questionratings
from rest_framework import viewsets
from .serializers import UserSerializer, PostSerializer, RepliesSerializer
from django.db.models import Avg,Sum


def RegisterView(request):
    form = RegisterForm(request.POST)
    login_form = LoginForm()
    register_form = RegisterForm()
    if request.method == 'POST':
        if form.is_valid():
            address = form.cleaned_data['address']
            lastname = form.cleaned_data['last_name']
            firstname = form.cleaned_data['first_name']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = User(first_name=firstname, last_name=lastname, email=email, address=address, password=password, username=username)
            user.set_password(password)
            user.save()
            if user is not None:
                return render(request, 'myapp/index.html', {'msg': "Successfully Registered", 'login_form': login_form})
            else:
                return render(request, {'msg': "Couldn't register"})


def LoginView(request):
    form = LoginForm(request.POST)
    register_form = RegisterForm()
    if request.method == 'POST':

        if form.is_valid():

            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                userdetail=User.objects.get(email=email)
                request.session['user_id'] = userdetail.id
                return HttpResponseRedirect('/post/')

def HomeView(request):
    if request.method == 'GET':
        return render(request, 'myapp/post.html')


def MainpageView(request):
    if request.method == 'GET':
        return render(request, 'myapp/index.html', {'login_form': LoginForm(), 'register_form': RegisterForm()})


class PostList(ListView):
    # model = Post
    # template_name = 'myapp/post_list.html'

    def get(self, request):
        post_list = Post.objects.all()
        page = request.GET.get('page', 1)

        paginator = Paginator(post_list, 5)
        try:
            post = paginator.page(page)
        except PageNotAnInteger:
            post = paginator.page(1)
        except EmptyPage:
            post =paginator.page(paginator.num_pages)

        return render(request, 'myapp/post_list.html', {'post_list': post})


class PostDetail(View):

    def get(self, request, pk):
        post_detail = Post.objects.get(pk=pk)

        reply = Replies.objects.all()
        try:
            ratings = Postratings.objects.filter(post_id=pk).aggregate(Avg('rate'))
            return render(request, 'myapp/post_detail.html',
                           {'post_detail': post_detail, 'replyform': ReplyPostForm, 'reply': reply,
                            'rating': ratings, 'rating_form': PostRateForm})
        except:
            return render(request, 'myapp/post_detail.html',
                          {'post_detail': post_detail, 'replyform': ReplyPostForm, 'reply': reply, 'rating_form': PostRateForm})

    def post(self, request, pk):
        reply_form = ReplyPostForm(request.POST)

        if reply_form.is_valid():
            text = reply_form.cleaned_data['text']
            reply = Replies(text=text, post_id=pk)
            reply.save()
            return HttpResponse("Replied!")
        else:
            return HttpResponse("Couldn't Replied!")


def postrateView(request, pk):
    form = PostRateForm(request.POST)
    if request.method == 'POST':

        if form.is_valid():
            rate = form.cleaned_data['rate']
            if Postratings.objects.filter(post_id=pk).filter(user_id=request.session['user_id']).exists():
                Postratings.objects.filter(post_id=pk).filter(user_id=request.session['user_id']).update(rate=rate)
                return HttpResponse("Rated!!")
            else:
                rating = Postratings(rate=rate, user_id=request.session['user_id'], post_id=pk)
                rating.save()
                return HttpResponse("Rated!!")

        else:
            return HttpResponse("Must rate from 1 to 5 only!!")


class PostCreate(View):
    # model = Post
    # form_class =PostForm
    # # fields = ['title', 'text', 'created_date', 'publish_date', 'photo']
    # template_name = 'myapp/post_new.html'
    # success_url = reverse_lazy('myapp:post_list')
    def get(self, request):
        post = Post.objects.all()
        post_form = PostForm()
        return render(request, 'myapp/post_new.html', {'post':post, 'post_form': post_form})

    def post(self, request):
        form = PostForm(request.POST,  request.FILES)

        if form.is_valid():

            title = form.cleaned_data['title']
            text = form.cleaned_data['text']
            created_date = form.cleaned_data['created_date']
            publish_date = form.cleaned_data['publish_date']
            photo = request.FILES['photo']
            form = Post(title=title, text=text, created_date=created_date, publish_date=publish_date, photo=photo)
            form.save()
            return HttpResponse("Posted")
            # return render(request, 'myapp/post_list.html', {'form': form})
        else:
            post_form = PostForm()
            # return HttpResponse("Form is not valid!!")
        return render(request, 'myapp/post_new.html', {'post_form': post_form})


class PostUpdate(UpdateView):
    model = Post
    fields = ['title', 'text']
    template_name = 'myapp/post_edit.html'
    success_url = reverse_lazy('myapp:post_list')

    #     total = form.cleaned_data['total']
    #     # post.save()
    #     if Postratings.objects.filter(post_id = pk).exists():
    #         rating = Postratings.objects.get(post_id = pk)
    #         rating.total = rating.total + total
    #         rating.rater_count = rating.rater_count + 1
    #         rating.average = rating.total/rating.rater_count
    #         rating.save()
    #     else:
    #         rating = Postratings(total=total, rater_count=1, average=total, post_id=pk)
    #         rating.save()
    #     return HttpResponseRedirect('/post/?message=rated&post&%s' % (pk))
    # else:
    #     return HttpResponse("Please rate from 1 to 10 only!!!")
    #


class PostDelete(DeleteView):
    model = Post
    template_name = 'myapp/post_delete.html'
    success_url = reverse_lazy('myapp:post_list')


class ReplyList(ListView):
    template_name = 'myapp/reply_list.html'
    model = Replies

    def get(self, request, pk):
        replies = Replies.objects.filter(post_id=pk)
    #      post_reply = Post.objects.get(post_id=pk)
        return render(request, 'myapp/reply_list.html', {'replies': replies, 'post_id': pk})
        # return render(request, 'myapp/reply_list.html', {'replies': replies})


class ReplyDetail(DetailView):
    model = Replies
    template_name = 'myapp/reply_detail.html'

    def get(self, request, pk):
        replies = Replies.objects.get(pk=pk)
        return render(request, 'myapp/reply_detail.html', {'replies': replies})


class ReplyCreate(CreateView):
    def get(self, request, pk):
        replies = Replies.objects.filter(pk=pk)
        reply_form = ReplyPostForm()
        return render(request, 'myapp/reply_new.html', {'replies': replies, 'reply_form': reply_form})

    def post(self, request, pk):
        reply_form = ReplyPostForm(request.POST)

        if reply_form.is_valid():
            text = reply_form.cleaned_data['text']
            created_date = reply_form.cleaned_data['created_date']
            reply = Replies(text=text, created_date=created_date, post_id=pk)
            reply.save()
            return HttpResponseRedirect('/reply/%s' % (pk))
        else:
            return HttpResponse("Couldn't Replied!")


class ReplyUpdate(UpdateView):
    model = Replies
    fields = ['post', 'text', 'created_date']
    template_name = 'myapp/reply_edit.html'
    # success_url = reverse_lazy('myapp:post_list')

    def get(self, request, pk):
        edit = Replies.objects.filter(pk=pk)
        edit_form = ReplyPostForm()
        return render(request, 'myapp/reply_edit.html', {'edit': edit, 'edit_form': edit_form})

    def post(self, request, pk):
        form = ReplyPostForm(request.POST)

        if form.is_valid():
            text = form.cleaned_data['text']
            created_date = form.cleaned_data['created_date']
            reply = Replies(text=text, created_date=created_date, post_id=pk)
            reply.save()
            return HttpResponseRedirect('/reply/%s' % (pk))
            # return HttpResponseRedirect('myapp:reply_list', kwargs={'pk':post.pk})


class ReplyDelete(DeleteView):
    model = Replies
    template_name = 'myapp/reply_delete.html'

    def get_success_url(self):
        post = self.object.post
        return reverse_lazy('myapp:reply_list', kwargs={'pk': post.pk})


class QuestionListView(ListView):
    def get(self, request):
        question_list = Questions.objects.all()
        return render(request, 'myapp/question_list.html', {'question_list': question_list})


class QuestionDetailView(DetailView):
    def get(self, request, pk):
        question_detail = Questions.objects.get(pk=pk)

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block body %}
{% endblock %}
{% if user.is_authenticated %}
<p><a href="{% url 'logout' %}">Logout</a></p>
</body>
{% endif %}
</html>

myapp/templates/myapp/post_delete.html
{% extends 'myapp/base.html' %}
{% block title %}Post delete{% endblock %}
{% block body %}
<h1>Post Delete</h1>
<form method="post">{% csrf_token %}
Are you sure you want to delete "{{post}}"?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

myapp/templates/myapp/post_detail.html
{% extends 'myapp/base.html' %}
{% block title %}Post Detail{% endblock %}
{% block body %}
<h1> Post Details</h1>
<h2>Title : {{post_detail.title}} </h2>
<h2>Rate: {{ rating.rate__avg }}</h2>
Text : {{post_detail.text}}
Created Date : {{post_detail.created_date}}
Published Date : {{post_detail.publish_date}}
    <br/>
Photo : <img src="{{ post_detail.photo.url }}" alt="image" width="100" height="100"/>
<br/>
Reply :
<form method="post">
    {% csrf_token %}
    {{replyform.text}}
    <input type = "submit" value="Submit"/>
</form>
Rate Post

<form method="POST" action="/post-rate/{{ post_detail.id }}">
        {% csrf_token %}
    {{ rating_form.rate }}
            <input type = "submit" value="Submit"/>
    </form>
{% endblock %}

myapp/templates/myapp/post_edit.html
{% extends 'myapp/base.html' %}
{% block title %}Edit POst{% endblock %}
{% block body %}
<h1>Post Edit</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type = "submit" value="Submit"/>
</form>
{% endblock %}

myapp/templates/myapp/post_list.html
{#{% load static %}#}
{#{% load ratings %}#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post List</title>
{#    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">#}
{#<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>#}

</head>
<body>
{% if user.is_authenticated %}
<h1>Post List</h1>

<table border="1">
<thead>
    <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Created Date</th>
    {% comment %}
    <th>Publish Date</th>
    {% endcomment %}
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
<!--    <th>Rate</th>-->
    <th>Replies</th>
    <th>Image</th>
    </tr>
</thead>
<tbody>
    number of posts:{{post_list|length}}
    {% for post in post_list %}
    <tr>
    <td>{{ post.title|title }}</td>
    <td>{{ post.text|capfirst|truncatechars:10 }}</td>
    <td>{{ post.created_date }}</td>
    {% comment "Optionalnote " %}
        <td>{{ post.publish_date }}</td>
    {% endcomment %}
    <td><a href="{% url 'myapp:post-detail' post.id %}">view</a></td>
    <td><a href="{% url 'myapp:post-edit' post.id %}">edit</a></td>
    <td><a href="/post-delete/{{post.id}}">delete</a></td>
<!--    <td><form method="post" action="/post-rate/{{ post.id }}">-->
<!--        {% csrf_token %}-->
<!--    {{ rating_form.rate }}-->
<!--            <input type = "submit" value="Submit"/>-->
<!--    </form>-->

<!--    </td>-->
    <td><a href="{% url 'myapp:reply_list' post.id%}">Replies</a></td>
    <td>{{ post.photo }}</td>
{#    <td>{% ratings post %}</td>#}
    </tr>
    {% empty %}
    <h2>Sorry, no athletes is this list</h2>
        {% ifchanged post.title %} {{post.title}} {% endifchanged %}
    {% endfor %}
</tbody>
</table>
<!--<ul class="pagination pagination-primary mt-4">-->
    <!--<li class="page-item active"><a class="page-link" href="javascript:void(0);">1</a></li>-->
    <!--<li class="page-item"><a class="page-link" href="javascript:void(0);">2</a></li>-->
    <!--<li class="page-item"><a class="page-link" href="javascript:void(0);">3</a></li>-->
    <!--<li class="page-item"><a class="page-link" href="javascript:void(0);">4</a></li>-->
    <!--<li class="page-item"><a class="page-link" href="javascript:void(0);">5</a></li>-->
<!--</ul>-->
<a href="/post-new/">New</a>
{% if post_list.has_other_pages %}
  <ul class="pagination">
    {% if post_list.has_previous %}
      <li><a href="?page={{ post_list.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in post_list.paginator.page_range %}
      {% if post_list.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if post_list.has_next %}
      <li><a href="?page={{ post_list.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
<p><a href="{% url 'logout' %}">Logout</a></p>
{% else %}
    <p> You are not logged in</p>
    <a href={% url 'myapp:main' %}>Login</a>
{% endif %}
</body>
</html>

myapp/templates/myapp/post_new.html
{% extends 'myapp/base.html' %}
{% block title %}New POst{% endblock %}
{% block body %}
<h1>Post New</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
{#    {{form.as_p}}#}
    Title:{{post_form.title}} <br />
     <br />
    text:{{post_form.text}} <br />
     <br />
    photo:{{post_form.photo}} <br />
     <br />
    created_date:{{post_form.created_date}} <br />
     <br />
    publish_date:{{post_form.publish_date}} <br />
 <br />
    <input type = "submit" value="Submit"/>
</form>
{% endblock %}

myapp/templates/myapp/question_detail.html
{% extends 'myapp/base.html' %}
{% block title %}Question Detail{% endblock %}
{% block body %}
<h1> Question Details</h1>
<h2>Question : {{question_detail.question}} </h2>
Published Date : {{question_detail.publish_date}}
<h2>Rate : {{ rating.rate__avg }}</h2>
    <br/>
<form method="post">
        {% csrf_token %}
    {{ rating_form.rate }}
            <input type = "submit" value="Submit"/>
    </form>
{% endblock %}

myapp/templates/myapp/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Question List</title>
</head>
<body>
{% if user.is_authenticated %}
<h1>Question List</h1>

<table border="1">
<thead>
    <tr>
    <th>Question</th>
    <th>Publish Date</th>
    <th>View</th>
<!--    <th>Edit</th>-->
<!--    <th>Delete</th>-->
    </tr>
</thead>
<tbody>
{% for question in question_list %}
    <tr>
        <td>{{question.question }}</td>
        <td>{{question.publish_date}}</td>
        <td><a href="{% url 'myapp:question-detail' question.id %}">view</a></td>
    </tr>
{% endfor %}
</tbody>
<a href="{% url 'myapp:question-new' %}">New</a>
<p><a href="{% url 'logout' %}">Logout</a></p>
{% else %}
    <p> You are not logged in</p>
    <a href={% url 'myapp:main' %}>Login</a>
{% endif %}
</body>
</html>

myapp/templates/myapp/reply_delete.html
{% extends 'myapp/base.html' %}
{% block title %}Reply delete{% endblock %}
{% block body %}
<h1>Reply Delete</h1>
<form method="post">{% csrf_token %}
Are you sure you want to delete "{{replies}}"?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

myapp/templates/myapp/reply_detail.html
{% extends 'myapp/base.html' %}
{% block title %}Reply Detail{% endblock %}
{% block body %}
<h1> Reply Details</h1>
<h2>Post : {{replies.post}} </h2>
Text : {{replies.text}}
Created Date : {{replies.created_date}}
{% endblock %}

myapp/templates/myapp/reply_edit.html
{% extends 'myapp/base.html' %}
{% block title %}Edit Reply{% endblock %}
{% block body %}
<h1>Reply Edit</h1>
<form method="post">
    {% csrf_token %}
    {{edit_form.text}}
    {{edit_form.created_date}}
    <input type = "submit" value="Submit"/>
</form>
{% endblock %}

myapp/templates/myapp/reply_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reply List</title>
</head>
<body>
<h1>
    Replies
</h1>
<table border="1">
<thead>
<tr>
    <th>Post</th>
    <th>Reply</th>
    <th>Created Date</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
</tr>
</thead>
<tbody>
{% for replies in replies %}
<tr>
    <td>{{ replies.post }}</td>
    <td>{{ replies.text }}</td>
    <td>{{ replies.created_date }}</td>
    <td><a href="/reply-view/{{replies.id}}">view</a> </td>
    <td><a href="/reply-edit/{{post_id}}">edit</a> </td>
    <td><a href="/reply-delete/{{replies.id}}">delete</a></td>

</tr>
{% endfor %}
</tbody>
</table>
<!--{% for replies in replies %}-->
<!--{% if forloop.first %}-->
<!--<a href="/reply-new/{{replies.post_id}}">New</a>-->
<!--{% endif %}-->
<!--{% endfor %}-->
<a href="/reply-new/{{post_id}}">New</a>
</body>
</html>

myapp/templates/myapp/reply_new.html
{% extends 'myapp/base.html' %}
{% block title %}Reply New{% endblock %}
{% block body %}
<h1>Reply New</h1>
<form method="POST">
    {% csrf_token %}
    Text:{{reply_form.text}}
    Created date:{{reply_form.created_date}}
    <input type = "submit" value="Submit"/>
</form>
{% endblock %}